"""empty message

Revision ID: 45a7f42023c9
Revises: 41dd3f0f3983
Create Date: 2024-08-17 21:44:40.775603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a7f42023c9'
down_revision = '41dd3f0f3983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aa', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('aa')

    # ### end Alembic commands ###
